//
// Created by wuyuncheng on 13/9/20.
//

#ifndef FALCON_INCLUDE_COMMON_H_
#define FALCON_INCLUDE_COMMON_H_

namespace falcon{
  #define PHE_FIXED_POINT_PRECISION 8
  #define PHE_MAXIMUM_FIXED_POINT_PRECISION 32
  #define PHE_FIXED_POINT_BASE 2
  #define SPDZ_FIXED_POINT_PRECISION 16

  enum FLSetting {HORIZONTAL_FL, VERTICAL_FL};
  enum PartyType {ACTIVE_PARTY, PASSIVE_PARTY};
}

#endif //FALCON_INCLUDE_COMMON_H_
