//
// Created by wuyuncheng on 13/9/20.
//

#ifndef FALCON_INCLUDE_COMMON_H_
#define FALCON_INCLUDE_COMMON_H_

#define PHE_FIXED_POINT_PRECISION 8
#define PHE_FIXED_POINT_BASE 10

#endif //FALCON_INCLUDE_COMMON_H_
